biblioseller/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('mainlib.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainlib/urls.py
from django.urls import path
from .views import (
    LibraryListView,
    create_library,
    LibUpdateView,
    LibDetailsView,
    index,
    add_image,
    add_money,
    delete_image_view)

app_name = "mainlib"

urlpatterns = [
    path('', index, name='index'),
    path('list/', LibraryListView.as_view(), name='lib-list'),
    path('create/', create_library, name='create-book'),
    path('list/<int:pk>/', LibDetailsView.as_view(), name="book-details"),
    path('list/<int:pk>/update/', LibUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/add_image/', add_image, name='add_image'),
    path('add_money/', add_money, name='add_money'),
    path('delete_image/', delete_image_view, name='delete_image'),
]

mainlib/models.py
from django.db import models


def image_directory_path(instance, filename):
    """функция для направления подгружаемых картинок в папку"""
    return f"books/{filename}"


class Category(models.Model):
    """
    Модель для категоризации списка книг
    """
    tittle = models.CharField(max_length=150)

    def __str__(self):
        return self.tittle


class Library(models.Model):
    """
    Модель для хранения базы различных книжек
    tittle: название
    description: опиисание
    peculiarities: для хранения нюансов связанных с изданием
    image: обложка (остальные фото связываются через вторую модель)
    stock: копии в запасе
    price: цена
    sale: учитывает количество проданных копий, для формирования списка популярности
    in_pc_link: ссылка на компьютере
    in_room_place: Где лежат копии в физическом хранилище

    archived: применяется для того чтобы временно убрать книжку из отображения
    """

    tittle = models.CharField(max_length=100, verbose_name='название')
    description = models.TextField(null=False, blank=True, verbose_name='описание')
    peculiarities = models.TextField(null=False, blank=True, verbose_name='нюансы')
    image = models.ImageField(upload_to='cover/', default='', blank=True, verbose_name='изображение')
    stock = models.IntegerField(default=0, null=False, verbose_name="запасы")
    sale = models.IntegerField(default=0, null=True, verbose_name="продано")
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2, null=False, verbose_name="цена")
    in_pc_link = models.TextField(verbose_name='ссылка на версию в хранилище')
    in_room_place = models.TextField(verbose_name='примерное расположение в доме')
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False, verbose_name='архивная')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True,
                                 related_name="books", verbose_name="категория")

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"

    def __str__(self):
        return f"Книжка {self.tittle}, остаток {self.stock}"

    # нужен сервис истории цены, куда складывается история изменения цены на продукт


class LibImages(models.Model):
    """
    Модель для хранения списка изображений под отдельную книжку
    для быстрого ответа на вопрос о качестве книги
    связывается с книгой по ключу
    """
    name = models.CharField(
        max_length=48, null=False, blank=True, verbose_name="описывающий текст"
    )
    product = models.ForeignKey(
        Library, on_delete=models.CASCADE, related_name="images", verbose_name="книга"
    )
    image = models.FileField(
        upload_to=image_directory_path, verbose_name="путь к изображению"
    )

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"

    def src(self):
        return self.image

    def __str__(self):
        return f"/{self.image}"


class LibTags(models.Model):
    """
    Модель для хранения связывающих тэгов
    так же подрузамевается хранение расхожих проблем, связанных с книжками
    """

    book = models.ForeignKey(Library, on_delete=models.PROTECT)
    tag = models.CharField(max_length=150)
    description = models.TextField()

    def __str__(self):
        return self.tag



class Money(models.Model):
    """
    Модель для хранения денег
    """
    now = models.IntegerField()
    mounth = models.IntegerField(null=True, default=0)
    all = models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.all

mainlib/forms.py
from django import forms
from .models import Library, LibImages, Money


class MoneyForm(forms.ModelForm):
    """форма добавления цифр на экран общей суммы"""
    class Meta:
        model = Money
        fields = ('now', )
        widgets = {
            'now': forms.NumberInput(),
             }

        def __init__(self, *args, **kwargs):
            super(Money, self).__init__(*args, **kwargs)
            for field in self.fields.values():
                field.required = False



class LibImagesForm(forms.ModelForm):
    """Форма добавления дополнительного изображения"""
    class Meta:
        model = LibImages
        fields = ('name', 'image')


class LibraryForm(forms.ModelForm):
    class Meta:
        model = Library
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'image': forms.FileInput(),
            'stock': forms.NumberInput(),
            'sale': forms.NumberInput(),
            'price': forms.NumberInput(),
            'in_pc_link': forms.TextInput(),
            'in_room_place': forms.TextInput(),
            'archived': forms.CheckboxInput(),
            'category': forms.Select(),
        }

        # Добавляем параметр required=False для каждого поля
        def __init__(self, *args, **kwargs):
            super(LibraryForm, self).__init__(*args, **kwargs)
            for field in self.fields.values():
                field.required = False

mainlib/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, UpdateView
from .models import Library, Money, LibImages
from .forms import LibraryForm, LibImagesForm, MoneyForm
from datetime import datetime, timedelta
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt


class LibraryListView(ListView):
    """Представление для просмотра всех книг списком"""
    template_name = 'mainlib/library_list.html'
    context_object_name = 'books'
    queryset = Library.objects.filter(archived=False)
    paginate_by = 20  # количество объектов на странице

    def get_queryset(self):
        """Форма поиска"""
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            queryset = queryset.filter(tittle__icontains=q)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(context['books'], self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


class LibDetailsView(DetailView):
    """Представление для просмотра детализации книжки"""
    template_name = "mainlib/lib_detail.html"
    model = Library
    context_object_name = "book"
    success_url = '/list/'

    def get_context_data(self, **kwargs):
        """Добавляет возможность подключения разных дополнительных изображений"""
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['images'] = self.object.images.all()
        context['form'] = LibImagesForm()
        return context

    def form_valid(self, form):
        self.object = self.get_object()
        form.instance.library = self.object
        form.save()
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.dispatch(request, *args, **kwargs)


class LibUpdateView(UpdateView):
    model = Library
    fields = "tittle", "price", "description", "stock", 'image', 'in_pc_link', 'in_room_place'
    context_object_name = "book"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "mainlib:book-details",
            kwargs={"pk": self.object.pk},
        )


def create_library(request):
    if request.method == 'POST':
        form = LibraryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('mainlib:lib-list')  # перенаправление на страницу со списком библиотек
    else:
        form = LibraryForm()
    return render(request, 'mainlib/create_new_book.html', {'form': form})


def add_image(request, pk):
    """Представление позволяющее добавлять дополнительное изображение к книге"""
    book = Library.objects.get(pk=pk)
    if request.method == 'POST':
        form = LibImagesForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.product = book
            image.save()
            return redirect('mainlib:book-details', pk=book.pk)
    else:
        form = LibImagesForm()
    return render(request, 'mainlib/add_image.html', {'form': form})


def add_money(request):
    if request.method == 'POST':
        form = MoneyForm(request.POST)
        if form.is_valid():
            money = form.save(commit=False)
            money.mounth += Money.objects.last().mounth + money.now
            money.save()
            # Обнуляем mounth каждые 30 дней
            last_month = Money.objects.last().mounth
            if last_month + 30 <= datetime.now().day:
                # Только сначала доход месяца перекидываем в общий
                money.all += money.mounth
                Money.objects.all().update(mounth=0)

            return redirect('mainlib:index')
    else:
        form = MoneyForm()
    return render(request, 'mainlib/add_money.html', {'form': form})


def index(request):
    money = Money.objects.last()  # получаем первый объект из модели Money
    context = {'money': money}

    return render(request, 'mainlib/main.html', context)

@csrf_exempt
def delete_image_view(request):
    if request.method == 'POST':
        image_id = request.POST.get('image_id')
        try:
            image = LibImages.objects.get(id=image_id)
            image.delete()
            return JsonResponse({'success': True})
        except LibImages.DoesNotExist:
            pass
    return JsonResponse({'success': False})

mainlib/templates/mainlib/add_image.html
{% extends 'mainlib/base.html' %}

{% block title %}
  Add image
{% endblock %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Добавить изображение</button>
</form>
{% endblock %}

mainlib/templates/mainlib/add_money.html
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Добавить деньги</button>
</form>

<a href="{% url 'mainlib:index' %}">Вернуться</a>

mainlib/templates/mainlib/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mainlib/templates/mainlib/create_new_book.html
{% extends 'mainlib/base.html' %}

{% block title %}
  Create book
{% endblock %}

{% block body %}
    <h1>Добавить книгу в список</h1>
    <form method="POST" action="{% url 'mainlib:create-book' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
    </form>
{% endblock %}

mainlib/templates/mainlib/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <meta charset="UTF-8">
    <title>Библиотека</title>
</head>
<body>
{% block body %}
    align="center"
  Base body
{% endblock %}
{% block application %}{% endblock %}

</body>
</html>

mainlib/templates/mainlib/lib_detail.html
{% extends 'mainlib/index.html' %}
{% load thumbnail %}

{% block title %}
  Книга #{{ book.tittle }}
{% endblock %}

{% block body %}
  <h1>Книга <strong>{{ book.tittle }}</strong></h1>
  <div>

  <div><a href="{% url 'mainlib:lib-list' %}">Вернуться к списку</a></div>

  <h3>{{ book.category }}</h3>
    <div>Описание: <em>{{ book.description }}</em></div>
    <br>  <div>Нюансы: {{book.peculiarities }}</div>
    <br><div>Цена: <h3>{{ book.price }}</h3></div>
    <div>Наличие: {{ book.stock }}</div>
    <div>Продано штук: {{ book.sale }}</div>
    <p>Обложка: </p>
          {% thumbnail book.image "325x240" crop="center" as im %}
            <img src="{{ im.url }}" alt="House {{ book.tittle }}">
          {% endthumbnail %}
      <div>_______</div>
    <div>Ссылка на компьютере: <link>{{ book.in_pc_link }}</link></div>
    <div>Примерное расположение на полках: {{ book.in_room_place }}</div>
    <div>Archived: {{ book.archived }}</div>
      <br>
    <div><a href="{% url 'mainlib:book-update' pk=book.pk %}">Изменить книгу</a>
    <a href="{% url 'mainlib:add_image' pk=book.pk %}"><h3>Добавить изображение</h3></a></div>


  </div>

{#  <div>#}
{#    <a href="{% url 'mainlib:achive' pk=book.pk %}">Архивировать (больше не показывать в списке)</a>#}
{#  </div>#}

    {% if images %}
        {% for image in images %}
          {{ image.name }}
          {% thumbnail image.image "325x240" crop="center" as im %}
                <img src="{{ im.url }}" alt="изображение">
            <p class="center"><a href="{{ image.image.url }}">увеличить</a></p>
          {% endthumbnail %}
            <p class="center"><button class="delete-image-button" data-image-id="{{ image.id }}">Удалить</button></p>
        {% endfor %}
    {% else %}
        <p>Изображений нет.</p>
    {% endif %}

{% block js %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
  $(document).ready(function() {
    $('.delete-image-button').click(function() {
      var imageId = $(this).data('image-id');
      $.ajax({
        url: '/delete_image/',
        type: 'POST',
        data: { 'image_id': imageId },
        success: function() {
          $('.image-container[data-image-id=' + imageId + ']').remove();
          setTimeout(function() {
            location.reload();
          }, 500);
        }
      });
    });
  });
  </script>
{% endblock %}



{% endblock %}

mainlib/templates/mainlib/library_list.html
{% extends "mainlib/index.html" %}
{% load thumbnail %}

{% block title %}
  Lib list
{% endblock %}

{% block body %}
  <div>
    <a href="{% url 'mainlib:create-book' %}">Добавить новую книжку</a>
      ....
    <a href="{% url 'mainlib:index' %}">Назад</a>
  </div>
    <br>
    <h3>Форма поиска</h3>
    <form method="get">
      <input type="text" name="q" placeholder="Поиск">
      <button type="submit">Найти</button>
    </form>
<h2><p class="center">Книжки</p></h2>
{% for book in page_obj %}
    <strong><p>{{ book.title }}</p></strong>
    <a href="{% url 'mainlib:book-details' pk=book.pk %}">
        <h2>{{ book.tittle }}</h2>
        <p>{% thumbnail book.image "220x220" crop="center" as im %}
            <img src="{{ im.url }}" alt="House {{ book.tittle }}">
        {% endthumbnail %}</p>
    </a>
    <p>Расположение на компьютере: {{ book.in_pc_link }}</p>
    <p></p>
    <p>Цена: {{ book.price }}</p>
    <p>_______</p>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">&lsaquo; предыдущая</a>
        {% endif %}

        <span class="current-page">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">следующая &rsaquo;</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
        {% endif %}
    </span>
</div>


  <div>
      <br>
    <a href="{% url 'mainlib:create-book' %}">Добавить новую книжку</a>
      <br>
  </div>

{% endblock %}

mainlib/templates/mainlib/library_update_form.html
{% extends "mainlib/base.html" %}

{% block title %}
    Изменение книги {{ book.tittle }}
{% endblock %}

{% block body %}

    <h2>Update product form: {{ book.name }}</h2>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>

    <div>
        <p><a href="{% url 'mainlib:book-details' pk=book.pk %}">Вернуться к описанию {{ book.tittle }}</a></p>
        <p><a href="{% url 'mainlib:lib-list' %}">Перейти к общему списку</a></p>
{#        <p><a href="{% url 'mainlib:archive' pk=book.pk %}">Заархивировать это</a></p>#}
    </div>

{% endblock %}

mainlib/templates/mainlib/main.html
{% extends "mainlib/index.html" %}
{% load thumbnail %}

{% block tittle %}
    Mainpage
{% endblock %}

{% block body %}
    <h1>Учет книжной полки</h1>
    <a href="{% url 'admin:index' %}"><h3>Администрирование</h3></a>
    <a href="{% url 'mainlib:lib-list' %}"><p align="center" style="color:#ff0099; font-size:30px"><h2>Общий список книг</h2></p></a>
    <div>За месяц заработано: {{ money.mounth }} рублей</div>
    <div>%добавить ссылку на какое-то подобие учета%</div>
    <a href="{% url 'mainlib:add_money' %}">добавить доход</a>
    </form>

{% endblock %}